services:
  gotify:
    image: gotify/server
    container_name: gotify
    # Política de reinicio:
    restart: unless-stopped   # Reinicia el contenedor salvo que lo pares manualmente.
    # Puertos (comentados):
    # No exponemos el puerto directamente porque el acceso se hará a través de un proxy inverso,
    # como Nginx Proxy Manager (NPMplus). Si necesitas acceder sin proxy, descomenta la siguiente línea.
    # ports:    
    #  - 8080:80
    volumes:
      - "./gotify_data:/app/data"
    # Red Docker:
    networks:
      - homelab   # Conecta a la red personalizada 'homelab'
    environment:
      - GOTIFY_DEFAULTUSER_NAME=${GOTIFY_DEFAULTUSER_NAME}
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_DEFAULTUSER_PASS}
      - TZ=Europe/Madrid



networks:
  homelab:
    external: true   # Usa una red Docker llamada 'homelab' que ya debe estar creada previamente.