services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./lidarr_config:/config
      - ${LIBRARY}/music:/musica    # Aquí lidarr guardará tu música descargada
      - ${LIBRARY}/downloads:/downloads # (opcional) para buscar releases recién descargados, igual que Radarr/Sonarr
  #  ports:
  #    - 8686:8686
    networks:
      - homelab
    
networks:
  homelab:
    external: true