version: '3.8'

services:
  # --- Base de datos MariaDB para Nextcloud ---
  db:
    image: mariadb:11.4
    container_name: nextcloud_db
    restart: unless-stopped

    # Configuración recomendada para Nextcloud (integridad y replicación)
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW

    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # Contraseña del root de MariaDB
      - MYSQL_DATABASE=${MYSQL_DATABASE}            # Nombre de la base de datos para Nextcloud
      - MYSQL_USER=${MYSQL_USER}                    # Usuario de la base de datos
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}            # Contraseña del usuario

    volumes:
      - ${NEXTCLOUD_DB_DIR}:/var/lib/mysql          # Carpeta donde se guardan los datos de la base de datos

    networks:
      - homelab

  # --- Redis (caché y aceleración de Nextcloud) ---
  redis:
    image: redis:7
    container_name: nextcloud_redis
    restart: unless-stopped

    networks:
      - homelab

  # --- Servicio principal de Nextcloud ---
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped

    # Puertos (comentados):  
    # El acceso a Nextcloud será a través de proxy inverso (por ejemplo Nginx Proxy Manager).  
    # Si necesitas pruebas directas, descomenta y define NEXTCLOUD_PORT en tu .env
    # ports:
    #   - ${NEXTCLOUD_PORT}:80

    # Espera a que los servicios db y redis estén listos antes de arrancar
    depends_on:
      - db
      - redis

    links:
      - db

    environment:
      # Datos de conexión a la base de datos (vienen del .env)
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=db

      # Usuario y contraseña del administrador inicial de Nextcloud
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}

      # Directorio de datos de Nextcloud dentro del contenedor
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - TZ=${TZ}   # Zona horaria

      # Dominios de confianza y nombre del servidor (opcional, mejora seguridad y accesibilidad)
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - APACHE_SERVER_NAME=${APACHE_SERVER_NAME}

    volumes:
      - ${NEXTCLOUD_DATA_DIR}:/var/www/html/data           # Carpeta para los archivos de usuario
      - ${NEXTCLOUD_CONFIG_DIR}:/var/www/html/config       # Configuración personalizada de Nextcloud
      - ${NEXTCLOUD_APPS_DIR}:/var/www/html/custom_apps    # Apps adicionales de Nextcloud
      - ${NEXTCLOUD_THEMES_DIR}:/var/www/html/themes       # Temas personalizados de Nextcloud

    networks:
      - homelab

networks:
  homelab:
    external: true  # Usa la red Docker 'homelab' ya existente
